### ISSUE TITLE
Text outside () should not be treated as a regex-pattern

### ISSUE THREAD

**Issue by mohamed4ch** [mohamed4ch/JustRoute#1]
Text outside () should **not** be treated as a regex-pattern, It should be **escaped** instead.

**Comment by metaloha** [comment]
This is advertised as being a regex-based router (with aliases), so I disagree - the entire router definition **should** be a regex. The parentheses simply denote the capture groups that get mapped to a parameter for your function.

Granted, I can't think of an example offhand where I wouldn't want to capture something in the URL that I'd have to describe via regex, but who knows :)
